name: Deploy to github pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version:  12.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Run deploy script
        run: |
          git config user.name "BojanSof" && git config user.email "bojan.drago@gmail.com"
          npm run deploy